/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelayRouteImport } from './routes/relay'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEventRouteImport } from './routes/api/event'

const RelayRoute = RelayRouteImport.update({
  id: '/relay',
  path: '/relay',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventRoute = ApiEventRouteImport.update({
  id: '/api/event',
  path: '/api/event',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/relay': typeof RelayRoute
  '/api/event': typeof ApiEventRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/relay': typeof RelayRoute
  '/api/event': typeof ApiEventRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/relay': typeof RelayRoute
  '/api/event': typeof ApiEventRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/relay' | '/api/event'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/relay' | '/api/event'
  id: '__root__' | '/' | '/relay' | '/api/event'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RelayRoute: typeof RelayRoute
  ApiEventRoute: typeof ApiEventRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relay': {
      id: '/relay'
      path: '/relay'
      fullPath: '/relay'
      preLoaderRoute: typeof RelayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event': {
      id: '/api/event'
      path: '/api/event'
      fullPath: '/api/event'
      preLoaderRoute: typeof ApiEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RelayRoute: RelayRoute,
  ApiEventRoute: ApiEventRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
